version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    environment:
      - DB_HOST=db
      - DB_NAME=newsportal
      - DB_USER=root
      - DB_PASSWORD=root
    depends_on:
      db:
        condition: service_healthy
    networks:
      - my_network

  db:
    image: mysql:8.0
    environment:
      MYSQL_DATABASE: newsportal 
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - my_network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 3

volumes:
  db_data:

networks:
  my_network:
    driver: bridge

